<a href="https://colab.research.google.com/github/udaykiran2427/Learning-Pytorch/blob/main/gettingstarted.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fundamentals


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


In [2]:
# creating tensors
#scalar
scalar = torch.tensor(7)
scalar
scalar.ndim


0

# New section

In [3]:
scalar.item()

7

In [4]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.shape
vector.ndim

1

In [6]:
#Creating a MATRIX
MAT = torch.tensor([[7,8],[1,2]])
MAT

tensor([[7, 8],
        [1, 2]])

In [7]:
MAT.ndim


2

In [8]:
MAT.shape

torch.Size([2, 2])

In [9]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [10]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

In [12]:
TENSOR.ndim

3

In [13]:
##Scalars and vectors in lower case, Matrix and Tensors in uppercase, for naming

###Random Tensors

In [14]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0331, 0.0586, 0.7100, 0.3051],
        [0.2141, 0.8346, 0.5373, 0.9990],
        [0.9450, 0.3575, 0.1222, 0.9820]])

In [15]:
image_sz_tensor = torch.rand(size=(224,224,3))
image_sz_tensor

tensor([[[0.3337, 0.8683, 0.6617],
         [0.2083, 0.1301, 0.8177],
         [0.7464, 0.8241, 0.2445],
         ...,
         [0.7993, 0.0764, 0.7401],
         [0.1368, 0.3991, 0.7793],
         [0.9703, 0.6599, 0.9727]],

        [[0.2519, 0.8041, 0.1443],
         [0.8687, 0.0521, 0.1945],
         [0.1158, 0.0950, 0.9497],
         ...,
         [0.0148, 0.9525, 0.8697],
         [0.4970, 0.2252, 0.4552],
         [0.4288, 0.3097, 0.2727]],

        [[0.7467, 0.3222, 0.2559],
         [0.4948, 0.2436, 0.0388],
         [0.7438, 0.2594, 0.1001],
         ...,
         [0.7398, 0.5279, 0.4694],
         [0.0930, 0.0204, 0.3411],
         [0.0968, 0.5655, 0.1498]],

        ...,

        [[0.1826, 0.7987, 0.9181],
         [0.1658, 0.3541, 0.2447],
         [0.1807, 0.9024, 0.2094],
         ...,
         [0.1930, 0.3697, 0.8713],
         [0.6698, 0.5785, 0.8033],
         [0.8219, 0.6711, 0.0122]],

        [[0.7998, 0.1171, 0.5341],
         [0.8080, 0.9078, 0.3614],
         [0.

In [16]:
image_sz_tensor.shape

torch.Size([224, 224, 3])

Zeroes and Ones in  a tensor

In [17]:
zero = torch.zeros(3,4)

In [18]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones  = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

Range of tensors

In [21]:
zero_to_ten=torch.arange(0,10)

In [22]:
ten_zeroes = torch.zeros_like(input=zero_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
#tensor data types
#float 32
float_32_tensor = torch.tensor([3.,6.,9.])
float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
some_tensor = torch.rand(3,4)

In [26]:
some_tensor

tensor([[0.8813, 0.6624, 0.4169, 0.3410],
        [0.6951, 0.8050, 0.1442, 0.9552],
        [0.1874, 0.1345, 0.6971, 0.0943]])

In [27]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8813, 0.6624, 0.4169, 0.3410],
        [0.6951, 0.8050, 0.1442, 0.9552],
        [0.1874, 0.1345, 0.6971, 0.0943]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


Manipulating Tensors
*Tensor operations
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [28]:
#Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [29]:
#Multiplu tensor by 10
tensor*10

tensor([10, 20, 30])

In [30]:
#Subtract 10
tensor-10

tensor([-9, -8, -7])

In [31]:
#multiplication using in built functions
torch.mul(tensor,10)
#torch.add(),torch.sub() etc...,

tensor([10, 20, 30])

Matrix Multiplication


In [32]:
print("element wise matrix multiplication")
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")



element wise matrix multiplication
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [33]:
print("Matrix Multiplication")
print(tensor,"*",tensor)
print(f"Equals: {torch.matmul(tensor,tensor)}")

Matrix Multiplication
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: 14


min max mean sum etc


In [34]:
x = torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [35]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [36]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [37]:
#torch.mean() requires a tensor of float 32
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [38]:
x.dtype, torch.sum(x),x.sum() #sum works for int 64 whereas mean doesnt

(torch.int64, tensor(450), tensor(450))

Finding the positional min and max

In [39]:
x.argmin(),x.argmax()

(tensor(0), tensor(9))

In [42]:

x = torch.arange(1.,10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [45]:
x_reshaped = x.reshape(3,3)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [46]:
#view is more like a reeference to the tensor, if we change the view of a tensor the original tensor changes too

In [51]:
z = x.view(3,3)
z,z.shape #same memory as original

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [52]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [58]:
#stack tensors on top
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [65]:
#squeeze and unsqueeze
#torch.squeeze() -  removes all single dimensions from a target tensor
x= torch.zeros(2,1,2,1,2)
y = torch.squeeze(x)
x.size(),y.size()

(torch.Size([2, 1, 2, 1, 2]), torch.Size([2, 2, 2]))

In [66]:
y=torch.squeeze(x,0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [67]:
y=torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1, 2])

In [70]:
y=torch.unsqueeze(x,2)
y.size()
#extra dimension at 2 of 1

torch.Size([2, 1, 1, 2, 1, 2])