<a href="https://colab.research.google.com/github/udaykiran2427/Learning-Pytorch/blob/main/gettingstarted.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fundamentals


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


In [2]:
# creating tensors
#scalar
scalar = torch.tensor(7)
scalar
scalar.ndim


0

# New section

In [3]:
scalar.item()

7

In [4]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.shape
vector.ndim

1

In [6]:
#Creating a MATRIX
MAT = torch.tensor([[7,8],[1,2]])
MAT

tensor([[7, 8],
        [1, 2]])

In [7]:
MAT.ndim


2

In [8]:
MAT.shape

torch.Size([2, 2])

In [9]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [10]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

In [12]:
TENSOR.ndim

3

In [13]:
##Scalars and vectors in lower case, Matrix and Tensors in uppercase, for naming

###Random Tensors

In [14]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7713, 0.1973, 0.0198, 0.8793],
        [0.8566, 0.2685, 0.1898, 0.2736],
        [0.1752, 0.5313, 0.5146, 0.4658]])

In [15]:
image_sz_tensor = torch.rand(size=(224,224,3))
image_sz_tensor

tensor([[[0.8925, 0.6640, 0.9616],
         [0.3365, 0.4952, 0.0076],
         [0.8604, 0.9723, 0.0489],
         ...,
         [0.9388, 0.3779, 0.4998],
         [0.1867, 0.9961, 0.2313],
         [0.6532, 0.5264, 0.3604]],

        [[0.7366, 0.9214, 0.3283],
         [0.6719, 0.6109, 0.8057],
         [0.3606, 0.2224, 0.0175],
         ...,
         [0.0806, 0.5168, 0.7241],
         [0.7118, 0.8405, 0.1103],
         [0.1248, 0.1884, 0.0876]],

        [[0.1276, 0.8055, 0.8247],
         [0.3081, 0.1347, 0.8636],
         [0.8895, 0.4844, 0.3839],
         ...,
         [0.7209, 0.2814, 0.6528],
         [0.0663, 0.4160, 0.2575],
         [0.0135, 0.5701, 0.0635]],

        ...,

        [[0.9586, 0.5018, 0.9881],
         [0.4465, 0.2082, 0.4295],
         [0.3865, 0.9650, 0.5945],
         ...,
         [0.7696, 0.9036, 0.4457],
         [0.4272, 0.6345, 0.2481],
         [0.8879, 0.3546, 0.8539]],

        [[0.0784, 0.7116, 0.3556],
         [0.1406, 0.8326, 0.8888],
         [0.

In [16]:
image_sz_tensor.shape

torch.Size([224, 224, 3])

Zeroes and Ones in  a tensor

In [17]:
zero = torch.zeros(3,4)

In [18]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones  = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

Range of tensors

In [21]:
zero_to_ten=torch.arange(0,10)

In [22]:
ten_zeroes = torch.zeros_like(input=zero_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
#tensor data types
#float 32
float_32_tensor = torch.tensor([3.,6.,9.])
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32