<a href="https://colab.research.google.com/github/udaykiran2427/Learning-Pytorch/blob/main/gettingstarted.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fundamentals


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


In [ ]:
# creating tensors
#scalar
scalar = torch.tensor(7)
scalar
scalar.ndim


0

# New section

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape
vector.ndim

1

In [ ]:
#Creating a MATRIX
MAT = torch.tensor([[7,8],[1,2]])
MAT

tensor([[7, 8],
        [1, 2]])

In [ ]:
MAT.ndim


2

In [ ]:
MAT.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
##Scalars and vectors in lower case, Matrix and Tensors in uppercase, for naming

###Random Tensors

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7995, 0.3953, 0.8040, 0.1321],
        [0.1834, 0.1686, 0.8054, 0.6907],
        [0.7768, 0.2469, 0.1037, 0.5262]])

In [ ]:
image_sz_tensor = torch.rand(size=(224,224,3))
image_sz_tensor

tensor([[[6.8005e-01, 3.3190e-01, 7.7372e-01],
         [3.3937e-02, 9.0792e-01, 5.0201e-01],
         [8.8907e-01, 5.9361e-02, 4.4294e-01],
         ...,
         [1.0891e-01, 4.9597e-01, 4.4392e-01],
         [6.5840e-01, 2.7922e-01, 1.6913e-01],
         [4.3674e-01, 7.7356e-01, 6.1977e-01]],

        [[9.1306e-01, 7.4666e-01, 2.8112e-01],
         [7.1373e-01, 6.8583e-01, 3.1954e-01],
         [3.6717e-03, 5.5899e-01, 1.0805e-01],
         ...,
         [8.2926e-01, 1.0702e-01, 1.7432e-01],
         [7.9872e-01, 4.4571e-02, 3.7837e-01],
         [8.0126e-01, 8.0427e-01, 8.0525e-01]],

        [[9.1419e-01, 8.4261e-01, 2.7346e-01],
         [3.2981e-01, 2.4143e-01, 2.5353e-01],
         [8.9109e-01, 8.2289e-01, 8.9112e-01],
         ...,
         [3.9114e-01, 1.0504e-01, 3.5393e-01],
         [1.2729e-01, 5.4978e-01, 7.4539e-01],
         [5.7730e-01, 2.0565e-01, 9.2538e-01]],

        ...,

        [[8.3110e-02, 3.4535e-01, 5.9455e-01],
         [2.1415e-03, 5.4499e-01, 6.8139e-01]

In [ ]:
image_sz_tensor.shape

torch.Size([224, 224, 3])

Zeroes and Ones in  a tensor

In [ ]:
zero = torch.zeros(3,4)

In [ ]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones  = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

Range of tensors

In [ ]:
zero_to_ten=torch.arange(0,10)

In [ ]:
ten_zeroes = torch.zeros_like(input=zero_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#tensor data types
#float 32
float_32_tensor = torch.tensor([3.,6.,9.])
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
some_tensor = torch.rand(3,4)

In [ ]:
some_tensor

tensor([[0.8649, 0.5814, 0.4070, 0.6164],
        [0.8280, 0.1680, 0.1380, 0.8006],
        [0.8188, 0.1161, 0.2085, 0.9507]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8649, 0.5814, 0.4070, 0.6164],
        [0.8280, 0.1680, 0.1380, 0.8006],
        [0.8188, 0.1161, 0.2085, 0.9507]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


Manipulating Tensors
*Tensor operations
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [ ]:
#Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
#Multiplu tensor by 10
tensor*10

tensor([10, 20, 30])

In [ ]:
#Subtract 10
tensor-10

tensor([-9, -8, -7])

In [ ]:
#multiplication using in built functions
torch.mul(tensor,10)
#torch.add(),torch.sub() etc...,

tensor([10, 20, 30])

Matrix Multiplication


In [ ]:
print("element wise matrix multiplication")
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")



element wise matrix multiplication
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
print("Matrix Multiplication")
print(tensor,"*",tensor)
print(f"Equals: {torch.matmul(tensor,tensor)}")

Matrix Multiplication
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: 14


min max mean sum etc


In [ ]:
x = torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
#torch.mean() requires a tensor of float 32
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
x.dtype, torch.sum(x),x.sum() #sum works for int 64 whereas mean doesnt

(torch.int64, tensor(450), tensor(450))