<a href="https://colab.research.google.com/github/udaykiran2427/Learning-Pytorch/blob/main/gettingstarted.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fundamentals


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


In [2]:
# creating tensors
#scalar
scalar = torch.tensor(7)
scalar
scalar.ndim


0

# New section

In [3]:
scalar.item()

7

In [4]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.shape
vector.ndim

1

In [6]:
#Creating a MATRIX
MAT = torch.tensor([[7,8],[1,2]])
MAT

tensor([[7, 8],
        [1, 2]])

In [7]:
MAT.ndim


2

In [8]:
MAT.shape

torch.Size([2, 2])

In [9]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [10]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

In [12]:
TENSOR.ndim

3

In [13]:
##Scalars and vectors in lower case, Matrix and Tensors in uppercase, for naming

###Random Tensors

In [14]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8364, 0.0959, 0.9070, 0.0603],
        [0.9827, 0.9784, 0.4130, 0.4058],
        [0.6371, 0.8043, 0.7713, 0.5696]])

In [15]:
image_sz_tensor = torch.rand(size=(224,224,3))
image_sz_tensor

tensor([[[1.4008e-01, 6.5794e-01, 4.6460e-01],
         [4.8120e-01, 1.9505e-01, 1.1591e-01],
         [5.4755e-01, 1.6488e-02, 3.7217e-01],
         ...,
         [4.9906e-01, 2.0166e-01, 3.2002e-02],
         [2.0193e-01, 2.4666e-01, 7.0151e-01],
         [3.4571e-01, 6.5066e-03, 2.8500e-01]],

        [[8.1008e-01, 1.4664e-01, 2.8743e-01],
         [9.0877e-01, 9.9166e-01, 5.4100e-02],
         [8.1091e-01, 4.7241e-01, 5.0804e-01],
         ...,
         [9.7961e-01, 8.0139e-02, 4.7040e-01],
         [6.5966e-01, 3.6378e-01, 7.5581e-01],
         [9.8988e-01, 9.5678e-01, 2.2695e-01]],

        [[7.4762e-01, 3.3335e-01, 8.8942e-02],
         [9.6739e-01, 5.5685e-01, 2.7729e-02],
         [4.6309e-01, 6.8472e-01, 5.1973e-01],
         ...,
         [2.3860e-01, 4.6606e-01, 6.4367e-01],
         [3.4825e-02, 1.1108e-01, 4.8994e-01],
         [7.5370e-04, 1.8058e-01, 2.9347e-02]],

        ...,

        [[6.2310e-01, 5.6968e-01, 3.4638e-01],
         [2.0695e-01, 1.0279e-02, 8.4406e-02]

In [16]:
image_sz_tensor.shape

torch.Size([224, 224, 3])

Zeroes and Ones in  a tensor

In [17]:
zero = torch.zeros(3,4)

In [18]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones  = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

Range of tensors

In [21]:
zero_to_ten=torch.arange(0,10)

In [22]:
ten_zeroes = torch.zeros_like(input=zero_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
#tensor data types
#float 32
float_32_tensor = torch.tensor([3.,6.,9.])
float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
some_tensor = torch.rand(3,4)

In [26]:
some_tensor

tensor([[0.2525, 0.9390, 0.7767, 0.6353],
        [0.3294, 0.7310, 0.7240, 0.1564],
        [0.9134, 0.1697, 0.2814, 0.3151]])

In [27]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2525, 0.9390, 0.7767, 0.6353],
        [0.3294, 0.7310, 0.7240, 0.1564],
        [0.9134, 0.1697, 0.2814, 0.3151]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


Manipulating Tensors
*Tensor operations
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [28]:
#Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [29]:
#Multiplu tensor by 10
tensor*10

tensor([10, 20, 30])

In [30]:
#Subtract 10
tensor-10

tensor([-9, -8, -7])

In [31]:
#multiplication using in built functions
torch.mul(tensor,10)
#torch.add(),torch.sub() etc...,

tensor([10, 20, 30])

Matrix Multiplication


In [32]:
print("element wise matrix multiplication")
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")



element wise matrix multiplication
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [33]:
print("Matrix Multiplication")
print(tensor,"*",tensor)
print(f"Equals: {torch.matmul(tensor,tensor)}")

Matrix Multiplication
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: 14


min max mean sum etc


In [34]:
x = torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [35]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [36]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [37]:
#torch.mean() requires a tensor of float 32
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [38]:
x.dtype, torch.sum(x),x.sum() #sum works for int 64 whereas mean doesnt

(torch.int64, tensor(450), tensor(450))

Finding the positional min and max

In [39]:
x.argmin(),x.argmax()

(tensor(0), tensor(9))

In [40]:

x = torch.arange(1.,10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [41]:
x_reshaped = x.reshape(3,3)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [42]:
#view is more like a reeference to the tensor, if we change the view of a tensor the original tensor changes too

In [43]:
z = x.view(3,3)
z,z.shape #same memory as original

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [44]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [45]:
#stack tensors on top
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [46]:
#squeeze and unsqueeze
#torch.squeeze() -  removes all single dimensions from a target tensor
x= torch.zeros(2,1,2,1,2)
y = torch.squeeze(x)
x.size(),y.size()

(torch.Size([2, 1, 2, 1, 2]), torch.Size([2, 2, 2]))

In [47]:
y=torch.squeeze(x,0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [48]:
y=torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1, 2])

In [49]:
y=torch.unsqueeze(x,2)
y.size()
#extra dimension at 2 of 1

torch.Size([2, 1, 1, 2, 1, 2])

In [50]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
x_original.shape,x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [51]:
#indexing with Pytorch


In [52]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [53]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [54]:
x[0][2]

tensor([7, 8, 9])

In [55]:

x[0][2][2]

tensor(9)

Pytorch and Numpy

In [56]:
import numpy as np
import torch
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [57]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [58]:
# Reproducibility (trying to take random out of random)

In [59]:
#seeding for random to get same random values
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

r_t_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
r_t_d = torch.rand(3,4)
print(r_t_c)
print(r_t_d)
print(r_t_c == r_t_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [60]:
#runing on gpu
torch.cuda.is_available()


True

In [61]:
device ="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [62]:
!nvidia-smi


Wed Sep 25 05:58:32 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8              12W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [63]:
torch.cuda.device_count()

1

Always set up device agnostic code, can find it by a single search


In [64]:
tensor =  torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [65]:
#move to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [66]:
#move back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])